<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="context" nsURI="http://www.palladiosimulator.org/pcm/confidentiality/0.1/"
    nsPrefix="context">
  <eClassifiers xsi:type="ecore:EClass" name="ConfidentialAccessSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="policyContainer" lowerBound="1"
        eType="#//policy/PolicyContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextcontainer" lowerBound="1"
        eType="#//model/ContextContainer" containment="true"/>
  </eClassifiers>
  <eSubpackages name="model" nsURI="http://www.palladiosimulator.org/pcm/confidentiality/context/model/0.1/"
      nsPrefix="model">
    <eClassifiers xsi:type="ecore:EClass" name="HierachicalContext" eSuperTypes="#//model/Context">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//model/HierachicalContext"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeDirection" eType="#//model/Direction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SingleAttributeContext" eSuperTypes="#//model/Context"/>
    <eClassifiers xsi:type="ecore:EClass" name="RelatedContextSet" eSuperTypes="#//model/Context">
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
          upperBound="-1" eType="#//model/Context"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Context" abstract="true" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="ContextContainer" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" upperBound="-1"
          eType="#//model/Context" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Direction">
      <eLiterals name="TOPDOWN"/>
      <eLiterals name="BOTTOMUP" value="1"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="policy" nsURI="http://www.palladiosimulator.org/pcm/confidentiality/context/policy/0.1/"
      nsPrefix="policy">
    <eClassifiers xsi:type="ecore:EClass" name="PolicyContainer" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="policies" upperBound="-1"
          eType="#//policy/Policy" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Policy" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contexts" upperBound="-1"
          eType="#//model/Context"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
